# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ChessApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ChessApp

  pod 'RxSwift', '6.0'
  pod 'RxCocoa', '6.0'

  target 'ChessAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
